#!/usr/bin/env python3
"""Final 200-word cut for v4."""
import sys
from pathlib import Path

P = Path("/opt/data/fuzzy-audiogram/cmbp_v2/manuscript_v4.qmd")
s = P.read_text(encoding="utf-8")

CUTS = [
("""Approaches that soften these boundaries have been proposed. Machine-learning classifiers predict the severity grade directly but predict the same crisp categories, and their internal representations are not inspectable [@achakulvisut2025]. Preclinical work in the same vein detects cochlear synaptopathy in mice from auditory brainstem responses [@ceriani2025], which is a different task from grading a human audiogram. Data-driven profiling recovers auditory phenotypes without offering an interpretable severity decision [@saak2022; @saak2025]. These methods answer a different question: the difficulty is not predicting the label more accurately but representing the underlying quantity in a way that preserves gradation and remains legible to a clinician.""",
 """Approaches that soften these boundaries have been proposed. Machine-learning classifiers predict the severity grade directly but predict the same crisp categories, and their internal representations are not inspectable [@achakulvisut2025]; preclinical work in the same vein detects cochlear synaptopathy in mice from auditory brainstem responses [@ceriani2025], a different task from grading a human audiogram. Data-driven profiling recovers auditory phenotypes without offering an interpretable decision [@saak2022; @saak2025]. These methods answer a different question: the difficulty is not predicting the label more accurately but representing the underlying quantity so it preserves gradation and remains legible to a clinician."""),

("""A Mamdani fuzzy inference system was developed and validated that maps pure-tone thresholds onto a continuous index while preserving the information crisp classification discards. On a held-out NHANES test set the FAI achieved weighted kappa 0.946 against the WHO reference and matched the crisp grade in 99.1% of clear cases. Three findings stand out. First, the system remains compatible with standard practice, aligning with the crisp reference when classification is straightforward. Second, the graded representation is a better classifier than the calibrated label built on top of it, its arg-max reaching kappa 0.9564 against 0.946. Third, the wider graded region improves rather than costs agreement, raising kappa by 0.019 and borderline agreement by 5.6 points with bootstrap intervals excluding zero.""",
 """A Mamdani fuzzy inference system was developed and validated that maps pure-tone thresholds onto a continuous index while preserving the information crisp classification discards. On held-out NHANES ears the FAI achieved weighted kappa 0.946 and matched the crisp grade in 99.1% of clear cases. Three findings stand out: the system remains compatible with standard practice; the graded representation is a better classifier than the calibrated label built on it, its arg-max reaching 0.9564; and the wider graded region improves rather than costs agreement, raising kappa by 0.019 and borderline agreement by 5.6 points with bootstrap intervals excluding zero."""),

("""The results are consistent with the computational audiology literature and qualify it. Machine-learning classifiers [@ceriani2025; @achakulvisut2025] achieve strong accuracy but are not inspectable, and clustering-based profiling [@saak2022; @saak2025] recovers data-driven phenotypes without offering an explicit decision a clinician can interrogate. This study adds that such comparisons are confounded when the target is a deterministic function of its inputs, and that graded outputs require proper scoring rules to be distinguished. No previously published fuzzy system integrates severity classification, configuration typing, asymmetry grading and temporal tracking in one inspectable framework validated with a participant-level split. The World Report on Hearing [@who2021] redefined the grades, lowering the normal boundary to 20 dB; the deployed system follows the 1997 six-grade schema because that remains the working standard in most reporting.""",
 """The results are consistent with the computational audiology literature and qualify it. Machine-learning classifiers [@achakulvisut2025; @ceriani2025] achieve strong accuracy but are not inspectable, and clustering-based profiling [@saak2022; @saak2025] recovers phenotypes without offering an explicit decision a clinician can interrogate. This study adds that such comparisons are confounded when the target is a deterministic function of its inputs, and that graded outputs require proper scoring rules to be distinguished. No previously published fuzzy system integrates severity classification, configuration typing, asymmetry and temporal tracking in one inspectable framework validated with a participant-level split."""),

("""The framework is portable by design. Additional inputs, such as speech audiometry, otoacoustic emissions and patient-reported outcomes, can be accommodated by adding membership functions and rules, and a web-based calculator with a REST API for EHR integration has been deployed for clinical evaluation. Future work will validate the system prospectively, explore neuro-fuzzy approaches (ANFIS) that learn rule parameters while remaining interpretable, and determine whether the graded index improves on the crisp grade as a predictor of speech-in-noise performance, hearing-aid outcomes or cochlear implant candidacy.""",
 """The framework is portable by design. Additional inputs can be accommodated by adding membership functions and rules, and a web-based calculator with a REST API for EHR integration has been deployed for clinical evaluation. Future work will validate the system prospectively, explore neuro-fuzzy approaches (ANFIS) that learn rule parameters while remaining interpretable, and determine whether the graded index improves on the crisp grade in predicting speech-in-noise performance, hearing-aid outcomes or cochlear implant candidacy."""),

("""The Fuzzy Audiometric Index provides a continuous, frequency-resolved, interpretable classification of hearing loss that preserves the gradation lost to crisp PTA thresholds. Validated on a held-out NHANES test set, it shows substantial agreement with WHO PTA-4 classification while preserving information on borderline cases, configuration and graded severity. The probabilistic benchmark demonstrates that this reference label is a deterministic thresholding of its input, so agreement cannot evidence the value of a graded representation; the membership vectors matched a gradient-boosted model on Brier score and calibration error and improved on log loss from less input.""",
 """The Fuzzy Audiometric Index provides a continuous, frequency-resolved, interpretable classification of hearing loss that preserves the gradation lost to crisp thresholds. Validated on held-out NHANES ears, it shows substantial agreement with the reference classification while preserving information on borderline cases, configuration and graded severity. The probabilistic benchmark shows that the reference label is a deterministic thresholding of its input, so agreement cannot evidence the value of a graded representation; the membership vectors matched a gradient-boosted model on Brier score and calibration error and improved on log loss from less input."""),

("""Analyses were performed in Python: the inference system used scikit-fuzzy v0.5.0, the comparators scikit-learn v1.9 and statsmodels v0.14, and statistical testing SciPy v1.18. The complete analysis is available as an open-source implementation, with the membership function construction, the inference pipeline and the verification scripts provided as executable code.""",
 """Analyses were performed in Python: scikit-fuzzy v0.5.0 for inference, scikit-learn v1.9 and statsmodels v0.14 for the comparators, SciPy v1.18 for testing. The complete analysis, including the membership construction, inference pipeline and verification scripts, is provided as executable open-source code."""),
]

applied, missed = 0, []
for old, new in CUTS:
    if old in s:
        s = s.replace(old, new, 1); applied += 1
    else:
        missed.append(old[:70].replace("\n", " "))
P.write_text(s, encoding="utf-8")
print(f"  applied {applied}/{len(CUTS)} cuts")
for m in missed:
    print(f"    MISSED: {m}...")
sys.exit(0 if not missed else 1)
